# ================================
# Server (Microservice) Container
# ================================
build_server:
	swift build

start_server:
	./.build/debug/ProductService

# ================================
# Full Environment
# ================================
start_env: build_server start_server